### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by garanews** [ctxis/CAPE#1]
Hello,
will you pull your modify to spender-sandbox git?
How can I merge your files with spender-sandbox and try?

**Comment by kevoreilly** [comment]
Hi garanews,
If I do make any changes to the underlying Cuckoo that might be beneficial, I will send a pull request to the spender-sandbox repository. For the moment, most of the current development is focused on CAPE packages or other features which are not relevant to pure Cuckoo.
You should not need to merge anything though, everything needed to get CAPE running should be present in this repository. Please let me know if you have any problems getting it set up.
Kind regards,
Kevin
