### ISSUE TITLE
Allow download of extracted config

### ISSUE THREAD

**Issue by bartblaze** [ctxis/CAPE#12]
Hey Kev,

Would be awesome if you were also able to download the config when the extraction package is used, instead of only the payload.

Example: https://cape.contextis.com/analysis/2367/

Cheers

**Comment by kevoreilly** [comment]
Hey mate! Sounds like a good idea, let me try and implement it. I guess the
big question is how to write it, perhaps simple tab-separated text will do
fine. At some point down the line I guess export to indicator format might
be cool too.

**Comment by bartblaze** [comment]
Kev,

Tab-separated text sounds great! Perhaps in the future, .csv format would be handy as well :)

Cheers!

**Comment by enzok** [comment]
I have a simple tab separated version of this if you're interested. These 2 commits are from my "Franken"-CAPE-Cuckoo fork, but they should work fine with CAPE master branch. This will create a text file with a rudimentary dump of the config file, and could certainly be enhanced.

6037eca54290d4054a8dabb851395ec50a9d5e02 - main commit
2d4d638bd0e553bcfeb1c05a6b9d4c54ca2dab35 - dump without list (optional)

**Comment by kevoreilly** [comment]
Hey enzok, sorry I've only just noticed this. Thanks a lot for the commits, I'll look to integrating them! Cheers.

**Comment by kevoreilly** [comment]
Hi enzo, I've looked at integrating these changes but alas your 'franken' fork is complicating my understanding of what's going on. Would it be possible for you to make a pull request with only the relevant changes? This should simplify things a bit which would be really helpful.

**Comment by kevoreilly** [comment]
Thanks enzo for the pull request - this has been now been integrated. It would be great down the line to have csv or other open ioc formats, but I'll close this issue for now.
