### ISSUE TITLE
Issue With Log Rotate

### ISSUE THREAD

**Issue by Spiralem** [ctxis/CAPE#120]
After I updated CAPE to the current one, Latest commit 2f5ca82, logging seems a bit wonky after log_rotate commit. Each item seems to be logged twice, once with the proper formatting and another with the default formatting, and logs from cuckoo.py is also similarity logged into process.log which is supposed to be for `CAPE/utils/process.py`.
```
2018-09-18 16:24:42,595 [root] DEBUG: Importing modules...
Importing modules...
2018-09-18 16:24:42,791 [root] DEBUG: Imported "signatures" modules:
Imported "signatures" modules:
```
Looking at `CAPE/lib/cuckoo/core/startup.py`, it seems that TimedRotatingFileHandler is implemented twice, one taking backupCount from config another using hardcoded 30 days.

**Comment by doomedraven** [comment]
can you try comment this our and let us know? https://github.com/ctxis/CAPE/blob/7c0c022a8a99e37028e7d6caea762c2ffb8ba083/lib/cuckoo/common/demux.py#L33

**Comment by doomedraven** [comment]
do git pull dup logging remove, but if it still try to comment that out what i told in previous comment

**Comment by kevoreilly** [comment]
Yeah that basicConfig line is the problem - just removed it and logs are back to normal.

**Comment by doomedraven** [comment]
ok great :)

**Comment by kevoreilly** [comment]
Should be fixed now - thanks for raising and help solving!

**Comment by Spiralem** [comment]
Ok, after git pull, the duplicated logging on the console is fixed.
But after I turn on `logging.enable` to allow log rotate, the duplicated logging on console shows up in the log file.
Could it be each log is written into the log file by both WatchedFileHandler and TimedRotatingFileHandler?
Also the same log from `cuckoo.log` is repeated in `process.log`.

**Comment by doomedraven** [comment]
do you have process=on in cuckoo.conf?

**Comment by Spiralem** [comment]
> do you have process=on in cuckoo.conf?

`process_result = off`
I am running another thread using this command `python utils/process.py -p 4 auto -d`

**Comment by doomedraven** [comment]
ok that was just in case, interesting, i will check that later after work

**Comment by doomedraven** [comment]
ok i have half of the fix, i found why it loggign into the process both loggers, but still don't see why duplicated

**Comment by doomedraven** [comment]
@Spiralem can you test this one? https://github.com/ctxis/CAPE/pull/122

**Comment by doomedraven** [comment]
thanks for testing :)
