### ISSUE TITLE
capemon crashing

### ISSUE THREAD

**Issue by enzok** [ctxis/CAPE#125]
This sample is crashing capemon, but not cuckoomon.

https://cape.contextis.com/analysis/17610/

**Comment by doomedraven** [comment]
check the error 0xc0000005 you will see funny stuff

`message: Exception 0xc0000005 reported at offset 0x22610 in capemon itself while accessing 0x0 from hook RtlDispatchException`

**Comment by kevoreilly** [comment]
This looks to be fixed now:

https://cape.contextis.com/analysis/17630

**Comment by doomedraven** [comment]
that it was?

**Comment by kevoreilly** [comment]
I suspect it was bugs I introduced into anti-vm registry checks which I fixed with
https://github.com/ctxis/capemon/commit/7d77f91648f38b267b12b05f91212a121650d242 - I should have updated the public instance sooner.

**Comment by enzok** [comment]
Awesome thanks for the quick fix!
