### ISSUE TITLE
Feature request: Download and run samples

### ISSUE THREAD

**Issue by geekscrapy** [ctxis/CAPE#126]
Any chance we could get a feature into CAPE to download (and then run) a file when given a URL? Probably via one of the enabled network routing options.

**Comment by kevoreilly** [comment]
Ok I have just pushed a new 'wget' package to allow this, along with a wget binary in 337e2a5689ea8ba67cc3ea4d995b87e2f638b0a2.

You now can submit the malware URL in the URL bar, choose wget package and it should do the rest - it will attempt to download the URL via wget then launch the file.

There is one major limitation still: the file doesn't appear in static analysis. As it was downloaded by wget it's not properly registered in cape as the file 'of interest' - at some point it would be nice to complete this by getting the static analysis working too.

**Comment by doomedraven** [comment]
implemented here https://github.com/kevoreilly/CAPE/pull/154

**Comment by kevoreilly** [comment]
![image](https://user-images.githubusercontent.com/22219888/66045435-a6fd3300-e51b-11e9-8531-7cfc6540d9dc.png)

Thank you @doomedraven!
