### ISSUE TITLE
Crashes on recent pulls

### ISSUE THREAD

**Issue by kevoreilly** [ctxis/CAPE#134]
There seems to be a couple of issues with some recent changes. I'm seeing this:

NoReverseMatch at /analysis/219/
Reverse for ' file ' with arguments '(u'droppedzip ', 219, u'0f5c19ddfd8238cf862f5036e8c9dab66875ed2b26cbb6c304eca6b2bb33d01e')' and keyword arguments '{}' not found. 0 pattern(s) tried: []

The problem line:
<a href="
      {% url " file " "droppedzip " analysis.info.id file.sha256 %}
      " class="btn btn-primary btn-small">Download ZIP</a>

Problem is gone on restoring analysis/views.py and the dropped index.html to an older one, looks like the new zip download feature but I haven't had a chance to dig any further.

**Comment by doomedraven** [comment]
thats weird im using the same version


```
grep -i samplezip . -r <- the sme for dropperdzip
./templates/analysis/overview/_file.html:                    <a class="btn btn-primary btn-small" href="{% url "file" "samplezip" analysis.info.id analysis.target.file.sha256 %}">Download ZIP</a>
Binary file ./analysis/views.pyc matches
./analysis/views.py:    elif category in ("samplezip", "droppedzip"):
./analysis/views.py:        if category == "samplezip":
```

and this are uniq lines

**Comment by kevoreilly** [comment]
Just updated django to latest, now can't even get the web server running! It is crashing horribly on startup now - think I broke django :(

**Comment by doomedraven** [comment]
yep the latest django is v2.x and the latest suported was 1.10 i think

**Comment by doomedraven** [comment]
well mine is 

>>> django.VERSION
(1, 10, 4, u'final', 0)

**Comment by kevoreilly** [comment]
Yup I'll give that version a go and let you know how I get on - cheers.

**Comment by kevoreilly** [comment]
Hmm still not working:

 File "/usr/local/lib/python2.7/dist-packages/ratelimit/middleware.py", line 2, in <module>
    from django.utils.importlib import import_module
django.core.exceptions.ImproperlyConfigured: WSGI application 'web.wsgi.application' could not be loaded; Error importing module: 'No module named importlib'

**Comment by doomedraven** [comment]
did you solve it?

**Comment by doomedraven** [comment]
ok that droppedzip just poped here, fixing

**Comment by doomedraven** [comment]
ok that was a problem of spaces

**Comment by kevoreilly** [comment]
Yeah all sorted now! Thanks
