### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by gra55h0pp3r** [ctxis/CAPE#14]
I'm trying to download the executable from analysis [#2053](https://cape.contextis.com/analysis/2053/), but unable too. I have download the dropped files, but I'm trying to get a copy of executable to reverse engineer it. Your assistance would be greatly appreciated.

I have been using cuckoo for many years, so I will be downloading CAPE and installing it in my malware lab.

**Comment by kevoreilly** [comment]
Hi gra55h0pp3r, I had to disable the download of submitted files as it was viewed as potentially dangerous, personally I think it's just to keep lawyers happy and the like so we aren't seen as distributing malware!

Anyway, email me on kevoreilly@gmail.com and I will send you the sample.

Glad to hear you will be giving CAPE a try! I'm keen to hear how you get on with it.

Cheers,

Kevin

**Comment by kevoreilly** [comment]
It's worth pointing out though that you shouldn't really need the main executable if CAPE has done its job. The payload should be ready to disassemble, so with that and the config you have it all ready to go!

**Comment by gra55h0pp3r** [comment]
Kevin,

I just sent you an email requesting a copy of the sample. I really do appreciate you sending me a copy of the main executable.  Yes, CAPE has done a really great job and was very helpful, but I'll doing static analysis and figuring out the encryption and decryption routines.

Once I get CAPE installed and running, I'll shot you with an email on how it's working for me and hopefully be able to contribute.

Thank!

Daniel
