### ISSUE TITLE
No Module Named ImageHash

### ISSUE THREAD

**Issue by xlxn2wxn** [ctxis/CAPE#15]
Hi. I'm trying to set up CAPE for a school project. I've followed the [following guide](https://infosecspeakeasy.org/t/howto-build-a-cuckoo-sandbox/27) to set up my environment. However, I've run into an issue when starting cuckoo.py:
```
  eeee e   e eeee e   e  eeeee eeeee 
  8  8 8   8 8  8 8   8  8  88 8  88 
  8e   8e  8 8e   8eee8e 8   8 8   8 
  88   88  8 88   88   8 8   8 8   8 
  88e8 88ee8 88e8 88   8 8eee8 8eee8

 Cuckoo Sandbox 1.3-CAPE
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 CAPE: Config and Payload Extraction
 github.com/ctxis/CAPE

2018-01-18 17:21:02,019 [root] CRITICAL: CuckooCriticalError: Unable to import plugin "modules.processing.deduplication": No module named imagehash
```
I have verified my installation of ImageHash as well as its dependencies. Any idea on what could be the issue? Any help would be appreciated. Thanks in advance.

**Comment by kevoreilly** [comment]
Hi xlxn2wxn, glad to hear you are interested in CAPE - I'm not sure how much help I can be here other than to say that as far as I can remember I installed ImageHash using pip, and the version I have running is 3.4. One thing that you could do as a workaround is to disable the image deduplication processing module, which means editing processing.conf and modifying the following lines:

# Deduplicate screenshots
[deduplication]
enabled = yes

If you set this to 'no' instead, it will remove the need for ImageHash, although obviously the ideal solution is to somehow fix that dependency. If you could supply more info as to how you installed it and what version you have, perhaps something will become apparent that you can fix.

Kind regards,

Kev O'Reilly

**Comment by xlxn2wxn** [comment]
Hi Kev, many thanks for your help on this matter. I have since reinstalled CAPE using the provided documentation in this repo, and it seems to work. Now I just need to troubleshoot my Nginx web server as I'm getting some bad gateway errors haha...

Thanks again and have a good day :-)
