### ISSUE TITLE
CAPE processing module taking a long time to complete

### ISSUE THREAD

**Issue by enzok** [ctxis/CAPE#176]
A recent change is causing the CAPE processing module to take much longer to complete. I've tried to isolate the issue running with debug, but haven't had much luck. I'm thinking it has something to do with the abstracts.py changes, but can't confirm.

I'm including a sample hash that has been stuck processing for over 30 minutes.
609ae52d7655c3c1f9e0b14503de4e440bbf59fd774196fb24f2a4449c83f220

**Comment by doomedraven** [comment]
I will check it thanks, wow 30 min, i will chexk asap today

**Comment by enzok** [comment]
Thanks. Let me know if you need more info from me.

**Comment by enzok** [comment]
It's an RTF doc that dropped about 28 files. Not sure if this has anything to do with it.

**Comment by doomedraven** [comment]
ok already at home, testing, FYI this is amazing tool to test bottlenecks https://github.com/uber/pyflame

**Comment by doomedraven** [comment]
i can't reproduce it, it works fine here, i need to improve the rtf data visualization, but apart of that it works pretty quickly, can you check in statistics tab the timing?

**Comment by enzok** [comment]
CAPE - 2068.009

**Comment by doomedraven** [comment]
hm so something is in cape.py would need to investigate ,but i will make sure i have all up to date
