### ISSUE TITLE
capemon fails to follow new thread created by java

### ISSUE THREAD

**Issue by enzok** [ctxis/CAPE#199]
This sample runs with legacy cuckoomon.dll 4c09b1ec812ad0d8be2bbd476d40dd57, but fails to follow CreateThread with Capemon.

This behavior occurs with other samples as well.

**Comment by kevoreilly** [comment]
Thanks - I've confirmed this is a problem with the CreateThread hook - I'll figure it out and fix it as soon as I can.

Cheers

**Comment by kevoreilly** [comment]
This is now fixed in a1f7e08f155b3bc1edc9a912803a736d5f2c7e9a.
