### ISSUE TITLE
Allow easy copy of binGraph diagrams from the webgui

### ISSUE THREAD

**Issue by geekscrapy** [ctxis/CAPE#201]
binGraph images are currently output as SVG. These images cannot be easily saved and shared. The proposal is to change the output to PNG. This creates a lossless image, but can be saved + shared easily.

Changes required: 
- https://github.com/ctxis/CAPE/blob/355789cda6cc7d94280d70792be078d54a8dd738/lib/cuckoo/common/graphs/binGraph/binGraph.py#L172 > change 'format' to 'png'

- https://github.com/ctxis/CAPE/blob/b772feabc759e358d6b6be5800f6169e74529885/web/analysis/views.py#L852 > mod variable name ```bingraph_svg_content``` to ```bingraph_png_content``` (and all other references)

-  ```bingraph_png_content``` needs to be base64 encoded so we can load this into the webpage with minimal effort
- https://github.com/ctxis/CAPE/blob/b772feabc759e358d6b6be5800f6169e74529885/web/analysis/views.py#L853 > mod variable name ```bingraph_svg_path``` to ```bingraph_png_path``` (and all other references)

- All references to ```graphs.bingraph.content``` in view templates need to be modified to display a base64 encoded image (data URI) (e.g. https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html)

**Comment by doomedraven** [comment]
Fot that we can expose dl in different format i have it in todo

**Comment by kevoreilly** [comment]
Fixed in https://github.com/kevoreilly/CAPEv2/commit/1059b72abdf92a4ba5a1e18844897867e7bbeccb
