### ISSUE TITLE
Asked to report this, here I guess?

### ISSUE THREAD

**Issue by Mincci** [ctxis/CAPE#202]
"Crashed cuckoomon during analysis. Report this error to the Github repo" 

pid: 832
message: Exception 0xc0000005 reported at offset 0x22a00 in capemon itself while accessing 0x0 from hook RtlDispatchException

https://cape.contextis.com/analysis/20393/

**Comment by kevoreilly** [comment]
Hi Mincci, thanks very much for letting me know about this. It's now fixed, see https://cape.contextis.com/analysis/20631 for another run with the same sample.

I appreciate the help!
Kev
