### ISSUE TITLE
KVM VM never stops

### ISSUE THREAD

**Issue by seanthegeek** [ctxis/CAPE#246]
When running any kind of analysis in a KVM VM, CAPE never stops the VM, and the analysis never changes state from `running` to `completed`.

**Comment by doomedraven** [comment]
It does

**Comment by seanthegeek** [comment]
When I submit an Emotet dropper Word document (sha256: cd4ae834983ff4189d1d0fd22e71a8b81476fe5e380faa14d106c906f34dbbb7) in a KVM Windows 7 VM with Office 2016 on a Ubuntu 18.10 (GNU/Linux 4.18.0-13-generic x86_64) host/cuckoo system , Word opens and the sample runs. After a few minutes Word is killed, but the VM is never killed even hours later, and status of the task is still `running`. 

The sample runs fine in the public instance of CAPE.

I think something is going wrong with the scheduler?

**Comment by seanthegeek** [comment]
This turned out to be an error with my system

**Comment by doomedraven** [comment]
What was the problem?

**Comment by seanthegeek** [comment]
Not sure honestly *blushes*. I rebooted the system once, same issue, rebooted again without any changes, and it works.
