### ISSUE TITLE
Emotet extraction doesn't run, analyses timing out.

### ISSUE THREAD

**Issue by pieterbork** [ctxis/CAPE#278]
I've recently deployed a local install of CAPE and was trying to compare results from the public CAPE instance with my local install to ensure everything was configured correctly. I'm using this Emotet analysis: https://cape.contextis.com/analysis/35761/, but when I run the same file through my local CAPE instance I don't see the Emotet parser running or extracting RSA key/list of IPs.

Here is my analysis log - [analysis.log](https://github.com/ctxis/CAPE/files/2852904/analysis.log)

The analysis.log above is for one of the only analyses that has run on my local instance without timing out, but on a majority of analyses the results show `Error: The analysis hit the critical timeout, terminating.` as well. I've looked at other tickets that report this issue, but I am able to ping bidirectionally between host and guest and don't see any error logs in the analysis.log or cuckoo.log other than this. My default timeout is 200s, but have also experienced timeouts at 400s and greater as well.

Any help on these issues would be greatly appreciated!

EDIT: I am using virtualbox as my manager whereas I noticed the public instance uses ESX.

**Comment by doomedraven** [comment]
that are not error, that just mean `The analysis hit the critical timeout, terminating.`  that's all
about sample itself: 
about extractor i will check tomorrow

**Comment by kevoreilly** [comment]
From the analysis log it looks like the payload(s) were captured ok. So it looks like the problem is in the processing stage. The first question is: does the Emotet Yara sig detect the payloads? This is necessary to trigger the parser - if the cape tab has marked a payload as Emotet then the signature has hit. This would suggest the problem is with the parser, which should have left something in the cuckoo.log. If you can find a reference to the parser being triggered in that log this could be helpful in diagnosing further.

**Comment by pieterbork** [comment]
Thanks for pointing me in the right direction. I found `[lib.cuckoo.common.objects] WARNING: Unable to import yara (please compile from sources)` in cuckoo.log, reinstalled yara/yara-python from source and CAPE is now extracting Emotet RSA keys/IPs. 

I am, however, now seeing errors for the Emotet parser in cuckoo.log even though it seems to be running correctly:

```
2019-02-12 17:45:53,454 [mwcp.reporter] ERROR: Error running parser /home/cuckoo/CAPE/modules/processing/parsers/mwcp/parsers:Emotet on bfdce1a1423ae12703b8a2db7053f16b
Traceback (most recent call last):
  File "/home/cuckoo/CAPE/modules/processing/parsers/mwcp/reporter.py", line 576, in run_parser
    parser.run(**kwargs)
  File "/home/cuckoo/CAPE/modules/processing/parsers/mwcp/parsers/Emotet.py", line 131, in run
    ip = struct.unpack('<I', filebuf[c2_list_offset:c2_list_offset+4])[0]
error: unpack requires a string argument of length 4
2019-02-12 17:45:53,454 [modules.processing.CAPE] INFO: CAPE: malwareconfig.com parser: No module named Emotet
2019-02-12 17:45:53,614 [modules.processing.CAPE] INFO: CAPE: Imported DC3-MWCP parser Emotet
2019-02-12 17:45:53,728 [mwcp.reporter] ERROR: Error running parser /home/cuckoo/CAPE/modules/processing/parsers/mwcp/parsers:Emotet on bfdce1a1423ae12703b8a2db7053f16b
Traceback (most recent call last):
  File "/home/cuckoo/CAPE/modules/processing/parsers/mwcp/reporter.py", line 576, in run_parser
    parser.run(**kwargs)
  File "/home/cuckoo/CAPE/modules/processing/parsers/mwcp/parsers/Emotet.py", line 131, in run
    ip = struct.unpack('<I', filebuf[c2_list_offset:c2_list_offset+4])[0]
error: unpack requires a string argument of length 4
2019-02-12 17:45:53,729 [modules.processing.CAPE] INFO: CAPE: malwareconfig.com parser: No module named Emotet
```

Unsure if this is a bug, but my issue is resolved - this ticket can be closed. I appreciate the quick response and help!

**Comment by kevoreilly** [comment]
It may be that the parser fails on some payloads, Emotet results in many so often the parser fails on some but works on others. Did it work overall (config in the ui)?

There could possibly be better handling of errors in the parser, and there is an improvement in the works for relocated payloads which should also improve things.

There is a requirements.txt although UPX was left out as it doesn't install with pip. Again this area could probably be improved, thanks for the feedback.

**Comment by pieterbork** [comment]
Yes, everything seems to be working overall. Emotet/Loki/Smokeloader all seem to be parsing out configs, even if there are some errors in cuckoo.log.

Appreciate all the work you've done on this project, thank you!
