### ISSUE TITLE
How to submit URL through web portal

### ISSUE THREAD

**Issue by seantree** [ctxis/CAPE#28]
Hi,

I didn't see any URL submit option in web portal do you please tell me how to submit the URL's through web portal.
.
Thanks & Regards
Seantree

**Comment by kevoreilly** [comment]
Hi Seantree - do you mean you don't have the URL tab on the submission page? 

![image](https://user-images.githubusercontent.com/22219888/36604525-d540a0e6-18b5-11e8-9f3a-c3149e1102cc.png)

This is what mine looks like although the VirusTotal submission isn't on by default. I've looked for a config option that might disable the URL tab but can't find one.

**Comment by seantree** [comment]
I have only File Tab Rest of the tabs are not available to me?

**Comment by kevoreilly** [comment]
Ah are you referring to the online demo instance at cape.contextis.com? The vms for that do not currently have real internet access so the URL feature wouldn't work. For that reason this tab has been removed - but I am hoping to get some form of real internet connection set up for it at some stage. In the meantime you might be better off to set up your own instance - if you allow the vms to connect to the internet then this feature will work.

**Comment by seantree** [comment]
@kevoreilly Hi I have setup CAPE on my physical machine. I am not talking about the online CAPE

**Comment by kevoreilly** [comment]
Hmm that is a puzzle then. The code for these tabs is in web\templates\submission\index.html but there is no setting for these tabs to be disabled:

<li class="active"><a href="#file" data-toggle="tab"><span class="glyphicon glyphicon-file"></span> File</a></li>
<li><a href="#quarantine" data-toggle="tab"><span class="glyphicon glyphicon-fire"></span> Quarantine File</a></li>
<li><a href="#url" data-toggle="tab"><span class="glyphicon glyphicon-globe"></span> URL</a></li>
{% if config.vt %}
<li><a href="#vtdl" data-toggle="tab"><span class="glyphicon glyphicon-cloud-download"></span> VirusTotal Download</a></li>
{% endif %}
<li><a href="#pcap" data-toggle="tab"><span class="glyphicon glyphicon-transfer"></span> PCAP</a></li>

**Comment by seantree** [comment]
Hi,
Kindly check the web.py I think they are calling some different file instead of index.html that you mentioned I checked the file in template folder of index.html. Index.html file code is Ok but I am in doubt regarding the web.py is calling some different html file.
I am attaching the screenshot of my web page.
.
Kindly check it.
![screenshot from 2018-02-28 12-43-45](https://user-images.githubusercontent.com/29730058/36774812-6e10badc-1c57-11e8-96be-66a341aee307.png)

**Comment by kevoreilly** [comment]
Hmm I am a bit baffled by this - unfortunately I have no idea what other html is being called in your case, I have never seen anything like this before I'm afraid.

**Comment by doomedraven** [comment]
that looks like https://github.com/ctxis/CAPE/blob/master/utils/web.py no?

**Comment by seantree** [comment]
@doomedraven yes it's looks like that  and its not calling the index.html file which contains the URL and other functionalities to analyse. anyone having any Idea how to solve this?

**Comment by doomedraven** [comment]
yup, you should to use this instead https://github.com/ctxis/CAPE/tree/master/web

with  ex: `python manage.py runserver 0.0.0.0:8000`

**Comment by seantree** [comment]
@doomedraven I already tried that also previously it generates an error

**Comment by doomedraven** [comment]
yup with output we can help you :)

**Comment by seantree** [comment]
Hi @doomedraven Thanks for the suggestion it works now I was doing the mistake while executing the manage.py .. Now you can close this issue. Thanks once again man :)

**Comment by doomedraven** [comment]
im not root here, but you have permission to close it ;)

**Comment by kevoreilly** [comment]
Thanks doomedraven for helping sort this out!

**Comment by doomedraven** [comment]
always glad to help :)

**Comment by seantree** [comment]
Hi @doomedraven and @kevoreilly sorry to reopen this issue, this is the error which I was talking about while running the file python ./manage.py runserver 0.0.0.0:8000 


Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named ratelimit

let me know how to fix this?

.
Thanks & Regards
Seantree

**Comment by seantree** [comment]
sorry again I fixed this issue by installing ratelimit
