### ISSUE TITLE
Tasks always pending

### ISSUE THREAD

**Issue by seanthegeek** [ctxis/CAPE#311]
I'm not sure what change broke this, but with the latest commit, me mile tasks never move beyond pending in the web UI, and cuckoo.py just sits there waiting for tasks.

**Comment by doomedraven** [comment]
Any log in debug mode?

**Comment by seanthegeek** [comment]
```
2019-03-11 16:12:12,419 [lib.cuckoo.core.database] DEBUG: Database error fetching task: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'priority desc, added_on' should be explicitly declared as text('priority desc, added_on')
```

Repeated over and over

**Comment by doomedraven** [comment]
as your error says, https://github.com/ctxis/CAPE/blob/master/lib/cuckoo/core/database.py#L617 there it fails, so an library update?

**Comment by seanthegeek** [comment]
Nope. Neither psycopg2 or libpq-dev have changed. I even rolled back to a previous commit. Noting has helped I have no idea what broke. :(

**Comment by seanthegeek** [comment]
Apparently this suppressed warning has been firing for four years. Ouch!

 https://github.com/sqlalchemy/sqlalchemy/issues/4538#issuecomment-471834170

**Comment by doomedraven** [comment]
Make sure it qorks with latest sqlalchemy :)

**Comment by seanthegeek** [comment]
Done. It does. :)

**Comment by doomedraven** [comment]
cool :) thanks
