### ISSUE TITLE
What the column "Package" in CAPE Sandbox "recent" section means?

### ISSUE THREAD

**Issue by rsslldblsnglll** [ctxis/CAPE#326]
Hi everyone,
can someone tell me what the column "Package" means in the table which contains the list of all samples submitted to CAPE sandbox?

<img width="206" alt="cape" src="https://user-images.githubusercontent.com/40487953/55866549-dccee980-5b80-11e9-9491-16941105330f.PNG">

Thank you.

**Comment by rsslldblsnglll** [comment]
Edit: for example I see some values like
-Injection
-Extraction
-pdf
-exe
and so on.

**Comment by doomedraven** [comment]
that are the packages with which sample was executed in vm, check https://github.com/ctxis/CAPE/tree/master/analyzer/windows/modules/packages

searchign by name in repo helps ;)

**Comment by rsslldblsnglll** [comment]
> that are the packages with which sample was executed in vm, check https://github.com/ctxis/CAPE/tree/master/analyzer/windows/modules/packages
> 
> searchign by name in repo helps ;)

Yes but why I see samples with different ID and Package values, but same md5? That means that the file is the same, but why there are two rows, one for an id_x and package value "exe" and one for an id_y and package value "extraction"?

<img width="900" alt="cape" src="https://user-images.githubusercontent.com/40487953/55867069-0e948000-5b82-11e9-8b1e-6f844b0b6dd6.PNG">

**Comment by doomedraven** [comment]
bcz that is the submitCAPE.py module, check confs and files in project

**Comment by rsslldblsnglll** [comment]
> bcz that is the submitCAPE.py module, check confs and files in project

So, I can't assert that the behavior is the sample between the two rows considered?

**Comment by kevoreilly** [comment]
Hi rsslldblsnglll, a feature of CAPE is that jobs can be triggered by previous jobs; if you submit an EXE and it triggers a behavioural signature, for example 'Injection' due to the fact that it does, for example, process hollowing, then a second job will be triggered with the Injection package with the goal of extracting the injected payload(s).

**Comment by kevoreilly** [comment]
For example the NanoCaore in https://cape.contextis.com/analysis/63169 triggers both Extraction and Injection packages in #63171 and #63172.

![image](https://user-images.githubusercontent.com/22219888/55868256-046f8300-5b7c-11e9-8b28-c12758834441.png)

**Comment by rsslldblsnglll** [comment]
> For example the NanoCore in https://cape.contextis.com/analysis/63169 triggers both Extraction and Injection packages in #63171 and #63172.
> 
> ![image](https://user-images.githubusercontent.com/22219888/55868256-046f8300-5b7c-11e9-8b28-c12758834441.png)

Thank you a lot.
Rossella
