### ISSUE TITLE
Some error output from agent.py command window 

### ISSUE THREAD

**Issue by Aragorn1106** [ctxis/CAPE#33]
I use VirtualBox with win7 as my guest machine and ubuntu 16.04 as my host.
When I submit the sample, there are errors below.
How can I fix?

2018-04-19 230404,000 [root] INFO Date set to 04-19-18, time set to 150404
2018-04-19 230404,015 [root] ERROR Traceback (most recent call last)
  File Cyxomlwanalyzer.py, line 1373, in module
    analyzer.prepare()
  File Cyxomlwanalyzer.py, line 991, in prepare
    svcpid = self.pids_from_process_name_list([services.exe])
  File Cyxomlwanalyzer.py, line 933, in pids_from_process_name_list
    proclist.append((proc.ImageName.Buffer[proc.ImageName.Length2], proc.UniqueProcessId))
ValueError invalid string pointer 0x03691CD000000000
Traceback (most recent call last)
  File Cyxomlwanalyzer.py, line 1373, in module
    analyzer.prepare()
  File Cyxomlwanalyzer.py, line 991, in prepare
    svcpid = self.pids_from_process_name_list([services.exe])
  File Cyxomlwanalyzer.py, line 933, in pids_from_process_name_list
    proclist.append((proc.ImageName.Buffer[proc.ImageName.Length2], proc.UniqueProcessId))
ValueError invalid string pointer 0x03691CD000000000

If someone know how to fix it, please tell me!
Thanks!!

**Comment by kevoreilly** [comment]
Fantastic - thank you doomedraven for solving this so quickly!

**Comment by doomedraven** [comment]
@kevoreilly you are welcome :)
