### ISSUE TITLE
rarfile Python module not installed in guest

### ISSUE THREAD

**Issue by bartblaze** [ctxis/CAPE#331]
Seems like an issue with the online version:

> Error: Analysis failed: The package "modules.packages.rar" start function raised an error: rarfile Python module not installed in guest.

Example: https://cape.contextis.com/analysis/67448/

**Comment by doomedraven** [comment]
@kevoreilly  maybe its time to merge sflock from dev? and remove all this old deps

**Comment by enzok** [comment]
You have to copy unrardll.exe and unrar.exe to your guest. I think migrating to Sflock might be the better long term solution.

**Comment by kevoreilly** [comment]
sflock is now an option that solves this - thanks guys for the work integrating this from Cuckoo 2!
