### ISSUE TITLE
upstream rooter

### ISSUE THREAD

**Issue by wizkidnc** [ctxis/CAPE#37]
just did a git pull for the latest update and when I tried to access the web ui I get the following error:

Request Method: | GET
ImportError
No module named rooter
/cuckoo/repos/CAPE/web/submission/views.py in <module>, line 29
/usr/bin/python
2.7.12

looked at the cuckoo repo and saw they have rooter.py and so I checked this one and didn't see it in the CAPE repo. Any assistance when you get time would be awesome.

**Comment by doomedraven** [comment]
https://github.com/ctxis/CAPE/blob/master/utils/rooter.py

**Comment by wizkidnc** [comment]
brain fog on my part. thanks @doomedraven

**Comment by wizkidnc** [comment]
So I just took a look at this and it is trying to import from core and that may be where my issue is I think.

**Comment by wizkidnc** [comment]
so possibly this is missing in CAPE I guess from the latest commit. I could however be wrong.

**Comment by enzok** [comment]
My bad. The rooter file is indeed missing from my commit. I will add it ASAIC.

**Comment by wizkidnc** [comment]
I really appreciate all you do. This sandbox is really awesome.

**Comment by enzok** [comment]
@wizkidnc The commit has been merged. Please check it out.

**Comment by Kuzuto** [comment]
I just updated the new merged.
I'm getting :

Traceback (most recent call last):
  File "cuckoo.py", line 138, in <module>
    test=args.test)
  File "cuckoo.py", line 63, in cuckoo_init
    init_rooter()
  File "/home/cuckoo/CAPE/lib/cuckoo/core/startup.py", line 657, in init_rooter
    if not Config("vpn").vpn.enabled and cuckoo.routing.route == "none":
AttributeError: Config instance has no attribute 'vpn'

If I rename conf/vpn.conf.py to vpn.conf as the other .conf files, it can load the config, but then gets 

Traceback (most recent call last):
  File "cuckoo.py", line 138, in <module>
    test=args.test)
  File "cuckoo.py", line 64, in cuckoo_init
    init_routing()
  File "/home/cuckoo/CAPE/lib/cuckoo/core/startup.py", line 782, in init_routing
    if not rooter("nic_available", cuckoo.routing.tor_interface):
  File "/home/cuckoo/CAPE/lib/cuckoo/core/rooter.py", line 23, in rooter
    if not os.path.exists(cfg.cuckoo.rooter):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

I can't see what's wrong, but it can't startup on my installation.

**Comment by enzok** [comment]
Ugh, sorry about that. My IDE must have appended the .py to that conf file. It should be vpn.conf.

As for the other error:

From the cuckoo.conf file:
```
# Path to the unix socket for running root commands.
rooter = /tmp/cuckoo-rooter
```
Have you started the rooter daemon?

I use the following script (make sure you sudo as rooter needs to run as root):

```
$CUCKOO_PATH=/opt/cuckoo

# Stop and Start rooter.py
pkill -f rooter.py
python $CUCKOO_PATH/utils/rooter.py /tmp/cuckoo-rooter &
```

**Comment by kevoreilly** [comment]
How's this shaping up? Any joy getting it sorted?

**Comment by enzok** [comment]
This was fixed (hopefully) in  #40.

**Comment by Kuzuto** [comment]
Ah .. Even Inetsim & Tor is set to "off" in cuckoo.py, the script still looks if the interface i valid.
Is it possible to skip the interface check, if you set it to "off" ?

**Comment by enzok** [comment]
I added a check for the enabled value in the conf file. Pull request submitted.

**Comment by kevoreilly** [comment]
Merged pull request - let me know if this fixes up all the issues!

**Comment by Kuzuto** [comment]
For me it all worked now 👍

**Comment by wizkidnc** [comment]
I am good too. Thanks! 


-Markis Vines

**Comment by kevoreilly** [comment]
Thanks for the help with this one guys. Closing :thumbsup:
