### ISSUE TITLE
Trickbot analysis fails

### ISSUE THREAD

**Issue by seanthegeek** [ctxis/CAPE#384]
See https://cape.contextis.com/analysis/87838/

https://cape.contextis.com/analysis/87837/

**Comment by doomedraven** [comment]
thats normal xD did you check the error that is lnk file that you upload and package expects exe 
https://github.com/kevoreilly/CAPE/blob/master/analyzer/windows/modules/packages/TrickBot.py

so FP, don't specify package and thats all ;)

**Comment by kevoreilly** [comment]
Hmm but that was triggered off a generic job that worked - so the logic in submitCAPE must be buggy. It has the following:

elif 'TrickBot' in detections:
            if parent_package == 'doc':
                package = 'TrickBot_doc'
            elif parent_package == 'exe':
                package = 'TrickBot'
 
So it should only trigger off docs or exes, at least that's the intention to prevent broken jobs like this (and to avoid creating loads of packages like generic-TrickBot just in case).

The ideal would be to trigger the same package as the parent job (i.e. generic) but with added options to handle it as TrickBot, i.e. dll=DumpOnApi.dll,dll_64=DumpOnAPI_x64.dll",dump-on-api=SetUnhandledExceptionFilter as this is all the TrickBot package does.

**Comment by doomedraven** [comment]
oh lost that was from parent, i though that was human submission my fail

well the sample is exe where trickbot is detected, but it not uploaded it, it uploaded parent file weird

**Comment by seanthegeek** [comment]
Also, isn't CAPE supposed to be able to carve out the configuration/C2 for Trickbot?

**Comment by doomedraven** [comment]
it is

**Comment by kevoreilly** [comment]
It seems the bad guys changed the static config storage somehow. If you check the parser in modules/processing/parsers/malwareconfig/TrickBot.py, it relies on the config being in the resource directory of the extracted PE payload. A quick look at recent samples would suggest that this may have changed - I haven't had time to dig into this one myself but would really appreciate it if you fancied trying to find out what has changed and what can be done to update the parser to work again. Too much to do and too little time :-(

**Comment by seanthegeek** [comment]
Sure. I'll admit static analysis isn't one of my strengths, but I'll give it a go. I know a few people who might be able to help to. Hopefully I'll get you a PR soon 😊

**Comment by sysopfb** [comment]
Kev is correct, they don't parse the config in the same way so dynamic ripping will be hit or miss at best.

Statically:
1: The bot has had the same obfucsation layer added to it as loader meaning every function is wrapped in protection so would probably need to wait until traffic happens before you rip the bot EXE from memory.
2: The decoding which is actually covered by an existing update to the config decoder by Graham Austin still works but you'll need to wait until the functions are unwrapped in memory but they are also rewrapped in memory after being used which once again makes this hit or miss.
3: There is no longer a MZ header though for the decoded bot from the loader piece.

Looks like they are actively designing their obfuscations now to defeat sandbox memory work.

**Comment by kevoreilly** [comment]
Fixed in https://github.com/ctxis/CAPE/pull/472/commits/3bf67f49ea9904fa3d7877cb260177be46f83d16

Example https://capesandbox.com/analysis/12581/
