### ISSUE TITLE
Integrate CAPE w/existing Cuckoo instance?

### ISSUE THREAD

**Issue by enzok** [ctxis/CAPE#4]
Very interested in this project. I have a spender-sandbox Cuckoo instance running in my environment (with some gently mods.) How hard do you think it would be to integrate CAPE with my Cuckoo instance? Or does CAPE need to run on it's own? Thanks.

**Comment by kevoreilly** [comment]
Hi Enzok, CAPE is fully self-sufficient, the integrating is already done with spender-sandbox. all you have to do is create a new directory along side your existing spender directory, copy your configs across, stop the spender python processes and start up the cape ones. It really should be that easy! Let me know how you get on.

**Comment by kevoreilly** [comment]
Actually that's not quite true. There are some extra config items such as the cape processing and reporting modules. So you will have to do a bit of merging for these with your existing configs.
