### ISSUE TITLE
Something Doesn't Look Right (Web UI)

### ISSUE THREAD

**Issue by hackdefendr** [ctxis/CAPE#400]
The web ui doesn't look right to me.  Its all text, no graphics.

I am using the systemd startup scripts with CAPE located /opt.

Machinery is KVM, Guest is Windows 10, CAPE version is latest as of today.

![image](https://user-images.githubusercontent.com/2224217/64208581-b75eb700-ce64-11e9-9a94-eb6a6407203a.png)

Screenshot attached.

**Comment by doomedraven** [comment]
stop systemd and try to start from web folder with `python manager.py runserver 0.0.0.0:8000` and verify if works ,than there is some problems with systemd file

**Comment by hackdefendr** [comment]
OK that seems to work properly.  The web page looks normal.

Could this be a gunicorn issue? That is what the systemd for the web piece is using.

`/usr/bin/python /usr/local/bin/gunicorn -b 0.0.0.0:8000 web.wsgi`

J

**Comment by hackdefendr** [comment]
Wait.  I just noticed this messgae:

`You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.`

So I ran that migrate command and restarted using systemd.  The web ui looks normal now.

**Comment by doomedraven** [comment]
cool, if solved, close ;)
