### ISSUE TITLE
ERROR: Failed to process packet: invalid header length

### ISSUE THREAD

**Issue by hackdefendr** [ctxis/CAPE#406]
I've google this error and there is no solution. 

Has anyone seen this error and solved it?

**Comment by YESIHACK** [comment]
First I would like to say you should appropriate @doomedraven for helping you. Your not the only person who Cape Server he has had to help fix. He helping Noobs(like me) as well as constantly making updates. Beggars can't be choosers. Your not paying him for customer support.

I've been following the previous thread  and want you to try the following.

![Capture](https://user-images.githubusercontent.com/10007104/64385719-24a94e00-d005-11e9-8468-895b9160429d.PNG)

If that doesn't fix the issue try investigating the Pcap.
/opt/CAPE/storage/analyses/1/dump.pcap

**Comment by hackdefendr** [comment]
@doomedraven never helped me.  He just told me to start over and use his script that doesn't work on Debian 10.

**Comment by hackdefendr** [comment]
I tried everything you suggested and still get lots of the same error.

Note...I started over this morning and reinstalled my OS, and a clean install of CAPE.  Still seeing the exact same errors.

**Comment by doomedraven** [comment]
@hackdefendr never helped you? rofl reread the other thread how much you fixed thanks to me, with now saying that you are the most __ungrateful person i had to help__.

@kevoreilly close this issues isn't CAPE related issue

**Comment by doomedraven** [comment]
and @hackdefendr i have bad news for you, debian in general isn't supported, if you would at least care to check the header of my script you would saw that or searched in issues

**Comment by kevoreilly** [comment]
Having just re-read the previous thread, it looks like doomedraven helped solve about ten separate issues all under the guise of a KVM problem. But the fact that he *tried* to help is the real point here, we can't ask for much more from a community-driven open source project.

I used to run cape on Linux Mint but got tired of similar tricky issues so took doomed's advice and switched to Ubuntu 18.04 LTS. It's now become the supported OS as no one has put more time in to making it work on any other platform than doomed. His script is now the best way. It would be great if more people helped improve the documentation, and maybe even cover how to solve issues with Debian. But we have bigger fish to fry trying to develop the sandbox. But if you want to fill that gap, be my guest.

This particular issue must be something to do with the dependencies/versions surrounding dpkt and the opening of pcaps - other than that all I can say is it's not an issue I've seen before, and this part of the sandbox has been working for a lot of people for a long time.

Enough of the flames though, from now on it's gonna be all positive, or it won't be put up with!

**Comment by hackdefendr** [comment]
So I think you are correct in that this is dpkt issue.  From what I read it seems that a new default with latest version of dpkt is to dump as pcap-ng. I have not confirmed this is what is happening, but everything I have read about this error points to that being the issue.

There is a method using hexdump to check the header, I will try this on Monday when I am back at work. It's the weekend, and I'm going to relax.

**Comment by hackdefendr** [comment]
What version of dpkt is running on your sandbox farm?  I'd like to try downgrading my dpkt to see if it makes a difference.  If that still fails I will dig in and see if I can't figure out how to force dpkt to capture pcap instead of pcap-ng.

**Comment by kevoreilly** [comment]
I'm on dpkt version 1.8.7 - might be worth a try.

**Comment by hackdefendr** [comment]
This issue has gone away under Ubuntu 18.04.

Closing issue.
