### ISSUE TITLE
virtualbox

### ISSUE THREAD

**Issue by wizkidnc** [ctxis/CAPE#42]
this may be a dumb question but I have read through the docs and am checking to see if the additional CAPE features/parser is setup to work with virtualbox?

**Comment by doomedraven** [comment]
Yes see conf folder

**Comment by kevoreilly** [comment]
There is no such thing as a dumb question! To be fair I haven't actually tested it on VirtualBox and recently learned that the debugger doesn't work on KVM, so I do wonder if this feature will work on VirtualBox or not....

**Comment by wizkidnc** [comment]
Hi Kev, 

Just wanted to report back that the debugger works in virtualbox.

**Comment by kevoreilly** [comment]
That is great news! Thanks very much for testing this and letting me know.
