### ISSUE TITLE
How to modify and regenerate .dll in the CAPE/analyzer/windows/dll folder

### ISSUE THREAD

**Issue by jeevansio** [ctxis/CAPE#434]
I recently work on a project that requires modification on these .dll files. Is there a way I can make some modification?

**Comment by kevoreilly** [comment]
Yes of course - the monitor dlls are currently compiled using Visual Studio 2017. If you clone the repository at https://github.com/kevoreilly/capemon then you should be good to go. Let me know if any issues or you need help with the modifications! I would be very interested to hear about your use case.

**Comment by jeevansio** [comment]
Great. Thanks a lot.
