### ISSUE TITLE
Behavioral analysis fails

### ISSUE THREAD

**Issue by ninewayhandshake** [ctxis/CAPE#438]
When analyzing some files CAPE fails to produce any behavioral information when running with the default loader. 

Here is a failed submission with the default loader.
https://cape.contextis.com/analysis/92394/

However when submitting with the old loader it works as expected.
https://cape.contextis.com/analysis/92395/

I've noticed this issue is quite frequent for me but it only seems to affect .NET binaries for whatever reason.

**Comment by ninewayhandshake** [comment]
Ive looked into this some more and I _think_ the issue comes from this check.

https://github.com/kevoreilly/capemon/blob/capemon/loader/loader/Loader.c#L553

And is related to the beahviour described here.

http://www.chilkatforum.com/questions/9610/dynamically-loading-a-32-bit-or-64-bit-net-assembly-at-runtime

Architechture mismatch occurs when a 32 bit .NET PE prefers to run as a 64 bit process.

There are a couple of workarounds that forces 32bit execution and that seems to work from the testing ive done. They are described here. 

https://stackoverflow.com/questions/619155/environment-variable-to-force-net-applications-to-run-as-32bit

Neither of the workarounds feels very good though so would it be possible to modify the loader to take this behaviour into account?

**Comment by doomedraven** [comment]
Hey thanks for interesting issue, @kevoreilly will can respond better as he is monitor master, but that is kinda integrated

https://github.com/ctxis/CAPE/blob/master/analyzer/windows/modules/packages/exe.py#L16

so you just need to put in options `runasx86=1`

**Comment by doomedraven** [comment]
so maybe we will need to force that for all non pe32+ samples? @kevoreilly  thoughts ?

**Comment by kevoreilly** [comment]
Very interesting - it does fail with "InjectDllViaIAT: Executable image invalid." so yeah it might be fixable just be loosening that check. Particularly if the old loader doesn't need the runasx86 option - I'll look into this and get back to you, thanks for letting us know.

**Comment by ninewayhandshake** [comment]
@kevoreilly Simply moving the APC injection handoff slightly avoids this issue altogether and has solved my problems. If you feel that solution is sufficient feel free to close this issue.

**Comment by kevoreilly** [comment]
I've loosened the check in the loader - thanks for bringing this to my attention!
