### ISSUE TITLE
No Cape extraction triggered on recent Emotet samples

### ISSUE THREAD

**Issue by Tomasuh** [ctxis/CAPE#448]
I submitted a few recent Emotet samples and noticed that no cape extraction triggered for any of them:
![image](https://user-images.githubusercontent.com/3432107/66477112-8e4ec900-ea97-11e9-8d5e-bb6d5000ecc7.png)

Examples:
https://cape.contextis.com/analysis/94278/
https://cape.contextis.com/analysis/94283/
https://cape.contextis.com/analysis/94280/

Does the Emotet config extractor need to be updated or am I doing something wrong?

**Comment by kevoreilly** [comment]
Thanks - I think there was something wrong with this instance (which I have no control over) but it seems to be fixed now.
