### ISSUE TITLE
Alembic not updating db properly

### ISSUE THREAD

**Issue by elmaisbuscado** [ctxis/CAPE#451]
i have attempted to run "alembic upgrade head" in order to update from 36926b59dfbb 
 to 30d0230de7cd. The script breaks, I'll show relevant errors on stacktrace:

[...]

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 36926b59dfbb -> 30d0230de7cd, options_255_to_1014
  File "<CAPE>/utils/db_migration/versions/options_255_to_1024.py", line 24, in upgrade
    existing_nullable=True)
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column

[...]

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "ALTER": syntax error
[SQL: ALTER TABLE tasks ALTER COLUMN options TYPE VARCHAR(1024)]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by doomedraven** [comment]
don't use sqlite3! that is dev database format for testing, there is warning for that, use proper database like postgres, we spoke with Kevin, i won't support that crap which is just for dev, use proper things and enjoy performance or write alembic for sqlite3 :P 

here you have how to install it
https://github.com/doomedraven/Tools/blob/master/Cuckoo/cuckoo.sh#L426
and here how to create db
https://github.com/doomedraven/Tools/blob/master/Cuckoo/cuckoo.sh#L473

then just change connection like showed here
https://github.com/doomedraven/Tools/blob/master/Cuckoo/cuckoo.sh#L596

**Comment by kevoreilly** [comment]
Yeah I was caught out by this but have managed to switch to psql without too much trouble. Although I just started with a fresh database, saving an existing one might not be so easy...

**Comment by doomedraven** [comment]
to get everything back to work, modify `lib/cuckoo/core/database.py` set schema to `36926b59dfbb` and then in options size back to 255 from 1024, but you will start getting luck of some features which required that upgrade

**Comment by elmaisbuscado** [comment]
Ok, is solved using Postgres. Maybe should remove sqlite3 support¿? This will breaks for everyone using sqlite3...

**Comment by doomedraven** [comment]
we spoke about to remove that, but no, people should read warnings when no connection is set, sqlite3 is useful for quick test of cape, or in some dev where you don't need db, you just want to make feature and forget

we have another alembic upgrade which we "postponed" due to that sqlite3 problem
