### ISSUE TITLE
Error when installing from requirements.txt

### ISSUE THREAD

**Issue by Spiralem** [ctxis/CAPE#458]
When trying to clean install CAPE using `pip install -r requirements.txt` I encountered the following error.

> ERROR: sflock 0.3.10 has requirement olefile==0.43, but you'll have olefile 0.45.1 which is incompatible.
> ERROR: sflock 0.3.10 has requirement python-magic==0.4.12, but you'll have python-magic 0.4.15 which is incompatible.
> ERROR: socks5man 0.2.0 has requirement PySocks==1.5.7, but you'll have pysocks 1.7.1 which is incompatible.
> ERROR: peepdf 0.4.2 has requirement jsbeautifier==1.6.2, but you'll have jsbeautifier 1.10.2 which is incompatible.
> ERROR: peepdf 0.4.2 has requirement Pillow==3.2.0, but you'll have pillow 6.2.1 which is incompatible.
> ERROR: jsbeautifier 1.10.2 has requirement six>=1.12.0, but you'll have six 1.11.0 which is incompatible.

**Comment by doomedraven** [comment]
what about `sudp pip install -r requirements.txt -U`

**Comment by Spiralem** [comment]
I am still getting the same error when using `pip install` with -U flag
I think is due to requirements.txt file listing ` olefile==0.45.1` while sflock 0.3.10 setup.py is listing `olefile==0.43`

**Comment by doomedraven** [comment]
well you can bump after install, we can't manage externals dependencies dependencies, it won't break if you install 0.45.1

**Comment by Spiralem** [comment]
> 
> 
> well you can bump after install, we can't manage externals dependencies dependencies, it won't break if you install 0.45.1

Ok, thanks.
