### ISSUE TITLE
x64 DLL Extraction module doesn't work

### ISSUE THREAD

**Issue by tsarpaul** [ctxis/CAPE#462]
The x64  DLL extraction module is redirected to the regular dll module.
Seems like this was done on purpose (re-enabling causes a crash in the guest injected dll) but this should be documented as an issue:
https://github.com/ctxis/CAPE/blame/dd6f3d482fe2d971220a79ed91acd759618cbb7c/analyzer/windows/modules/packages/Extraction_dll.py#L21

**Comment by kevoreilly** [comment]
This was a mistake to comment out the 64-bit dll in Extraction-related packages - thank you for pointing it out. I have fixed this in https://github.com/kevoreilly/CAPE/commit/134547d5dc3c5b4a0464de510c86bc7ab58c495f

I haven't had any issues with the 64-bit Extraction monitor but please do raise an issue if you can recreate on capesandbox.com
