### ISSUE TITLE
Which commit was capemon.dll compiled from

### ISSUE THREAD

**Issue by tsarpaul** [ctxis/CAPE#463]
Hi, I'm trying to compile my own capemon.dll using https://github.com/kevoreilly/capemon but it crashes during runtime (also other commits aswell). Which exact commit/version was used to compile the capemon.dll used in this repository?

I could attach the analysis.log but I'm currently not on my main computer. Might be a problem in my edited capemon so I'm not sure if it's relevant. Just want to know which version of capemon to test it against :)

**Comment by kevoreilly** [comment]
Hi Paul, the very latest commit is the one used to compile capemon. So I'm not sure what might be causing your issue, just in case I used VS 2017 with the latest updates.

If you have modified the code then I would suggest trying first without mods. If that doesn't work then please try and let me know any further details from the logs. Sometimes the RVA of the crash in capemon can be used to pinpoint the area in the source responsible for the crash.

**Comment by tsarpaul** [comment]
Cool, I thought it might've been an integration issue since the dates which have capemon.dll compiled are earlier than the most recent commits.

It was an issue on my end: the same patch I placed on NewExtraction branch:
https://github.com/tsarpaul/capemon/commit/ba3c555a53fd838954ad4ecccf87212e2d5c03d7

Didn't work on capemon for some reason so I did something else.
(I'm speeding up the environment by disabling behavior logging)

**Comment by kevoreilly** [comment]
That's probably commits where the only code changes were to the loader so these were the only updated binaries.

**Comment by kevoreilly** [comment]
Actually it could be that i committed changes which failed in testing when trying to integrate the behavioural extraction code into the main monitor. I will hopefully complete this work soon but have to be very careful with changes to the monitor binaries as they are complex, sensitive and critical.
