### ISSUE TITLE
File not detected as being in VT

### ISSUE THREAD

**Issue by wesinator** [ctxis/CAPE#467]
https://cape.contextis.com/analysis/114178/
submission `2019-11-29 00:37:35`
VT tab shows `This file is not on VirusTotal.`

https://www.virustotal.com/gui/file/0f0f51d50dfb4912991537df670c158f8191e81c8280043c19fd6f40b3d78aed/details
VT first submission `2019-07-25 08:11:52`

**Comment by kevoreilly** [comment]
Hmm that's obviously not how it's supposed to be. Perhaps this instance has not been configured properly to do the VT checks. It's working at https://capesandbox.com/analysis/9687

**Comment by kevoreilly** [comment]
I'm going to close this as it's working in the code - this was an issue with the contextis instance which I have no control over.
