### ISSUE TITLE
Agent.py

### ISSUE THREAD

**Issue by phunki32** [ctxis/CAPE#473]
Hi,

I've been trying to install CAPEv2 over the last few days and seem close to my objective :)
The new cape2.sh and kvm-qemu.sh (04.03.20) were used on fully updated (05.03.20) Ubuntu LTS18.04. I had different issues, notably with MongoDB which was not functioning correctly. 

MongoDB solution for me was to 
systemctl disable mongodb.service 
and use 
mongod --dbpath /opt/CAPEv2/db

But now my issue is with the agent.py on a win7 machine. The agent is started but cape (python3 cuckoo -d) cannot communicate. When I curl the guest I get:

<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 501.
<p>Message: Unsupported method ('GET').
<p>Error code explanation: 501 = Server does not support this operation.
</body> 

I believe it is a python2.7 (agent) to python3 issue. But still looking into it. Is there anything else I should check before?
Thank you for your work and help!

**Comment by bartblaze** [comment]
Probably better to report this in the CAPEv2 repo:
https://github.com/kevoreilly/CAPEv2/issues

**Comment by kevoreilly** [comment]
Please close this issue here if you can, as it pertains to v2, thanks.
