### ISSUE TITLE
Implement more anti-anti-vm features

### ISSUE THREAD

**Issue by bartblaze** [ctxis/CAPE#5]
Hey,

Great project. I ran [PaFish](https://github.com/a0rtega/pafish), which had the following outcome:

> [pafish] Start
> [pafish] Windows version: 6.1 build 7601
> [pafish] CPU: GenuineIntel (HV: VMwareVMware) Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60GHz
> [pafish] CPU VM traced by checking the difference between CPU timestamp counters (rdtsc) forcing VM exit
> [pafish] CPU VM traced by checking hypervisor bit in cpuid feature bits
> [pafish] CPU VM traced by checking cpuid hypervisor vendor for known VM vendors
> [pafish] VMware traced using MAC address starting with 00:05:69, 00:0C:29, 00:1C:14 or 00:50:56
> [pafish] End

Submission:
https://cape.contextis.com/analysis/558/

Cheers

**Comment by kevoreilly** [comment]
Hi bart, thanks for this suggestion. As it happens I just discussed this in a thread on spender-sanbox: https://github.com/spender-sandbox/cuckoo-modified/issues/459 which concludes with a way to clear the 'hypervisor' bit in VMware systems to pass a test in Pafish. I will look at implementing this and other possible fixes to try and get past these tests.

Cheers!

**Comment by bartblaze** [comment]
May be of help as well, ran [Al-Khaser](https://github.com/LordNoteworthy/al-khaser) a few days back, see analysis task [#2675](https://cape.contextis.com/analysis/2675/) 

Cheers!

**Comment by redsand** [comment]
I feel the role of this is at the virtualization layer and the process of deploying your test machines.

I have an attached script I've written (based upon @doomedraven script for debian) that will work on centos 7.

[kvm-qemu-antivm-patch.sh.txt](https://github.com/ctxis/CAPE/files/2133853/kvm-qemu-antivm-patch.sh.txt)

**Comment by doomedraven** [comment]
Hey cool stuff, can i use it in my blog with thanks to you?

**Comment by redsand** [comment]
Sounds fine to me! Just mention Tim Shelton (redsand) @ HAWK (hawk.io)

Nice to meet you, btw. 

I’m in dallas, tx. 

Tim

**Comment by doomedraven** [comment]
Cool, thanks, nice to meet you too, Im from UA

**Comment by doomedraven** [comment]
@redsand i have published how to install latest qemu/kvm with libvirt etc and not break nothing, https://gist.github.com/doomedraven/41af84c8cf93ba63cea933a80e898fb6
works much faster than previos versions, and allows to have all fixes :)
waiting for qemu 3 :)

**Comment by doomedraven** [comment]
FYI tested on ubuntu 16 and 18, works just fine

**Comment by redsand** [comment]
Awesome! Thanks for the mention!

Tim

**Comment by doomedraven** [comment]
you are welcome :)

**Comment by redsand** [comment]
Can you link me for details? I patched a bunch of stuff and tried many more
things. Lol

**Comment by doomedraven** [comment]
in that your .txt attachmed is like this, but that just a comment

```
 void helper_vmexit(CPUX86State *env, uint32_t exit_code, uint64_t exit_info_1)
 {
+    // env->tsc_offset -= 1000;
 }

 void cpu_vmexit(CPUX86State *nenv, uint32_t exit_code, uint64_t exit_info_1)
EOF
```


in qemu3 

```
void cpu_vmexit(CPUX86State *nenv, uint32_t exit_code, uint64_t exit_info_1,
                uintptr_t retaddr)
{
    assert(0);
}
```

**Comment by kevoreilly** [comment]
This issue I think has been addressed by @doomedraven in the fantastic KVM install script at https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh. If anyone is having issues with VM detection, the advised hypervisor to minimise this is KVM using this script.
