### ISSUE TITLE
Generic package launching Adobe Acrobat reader

### ISSUE THREAD

**Issue by enzok** [ctxis/CAPE#51]
A task is submitted as the generic package type when Cuckoo can't determine its type by extension or file magic. This is resulting in Adobe Acrobat Reader to run. Of course when Reader runs it generates a lot of false positives, despite configuring it not to.

Any ideas why this is happening?

**Comment by doomedraven** [comment]
That is windows settings, check default app for opening unknown stuff

**Comment by enzok** [comment]
I figured it might be. Thanks.
