### ISSUE TITLE
New version of Trickbot not parsing config

### ISSUE THREAD

**Issue by enzok** [ctxis/CAPE#57]
The latest Trickbot samples are giving the following error:

```
CAPE: malwareconfig parsing error with TrickBot: not well-formed (invalid token): line 1, column 0
```

I haven't had the time to look into the samples manually to see what may have changed.

Here's some of the sample MD5s:
d2d7a0384f6a5e4e7a2eb59a5f4488da
9979eb8a5e2c4fd32938497e6d4f896b

**Comment by kevoreilly** [comment]
This should now be fixed - thanks for the hashes.

https://cape.contextis.com/analysis/16308
https://cape.contextis.com/analysis/16312

**Comment by cy83rs30rd** [comment]
Awesome work, thanks.

**Comment by enzok** [comment]
Nice work. I'll go ahead and close this one out.
