### ISSUE TITLE
Windows 10 

### ISSUE THREAD

**Issue by enzok** [ctxis/CAPE#64]
Any consideration for a Windows 10 capable cuckoomon?

**Comment by kevoreilly** [comment]
I haven't tested a full setup, but I have tested capemon and the new loader on Windows 10. It seems to inject into processes no problem, although loading a new process seems not to load a window for something like notepad so there are perhaps issues to iron out there, but still the process runs and the monitor loads. 

Definitely something I want to be compatible with so I will need to test it further.

**Comment by enzok** [comment]
Thanks. I'll build one and see how it goes.

**Comment by kevoreilly** [comment]
Great - let me know. Be sure to try the new loader by renaming newloader* to loader* in the bin folder!

**Comment by doomedraven** [comment]
im gonna also try it :) thanks

**Comment by doomedraven** [comment]
hey from my previos tests when we added fixes to dll, and i just tested new loader again, im having the same issue, no behavior on win7

```
INFO: Successfully executed process from path "C:\Program Files\Microsoft Office\Office12\WINWORD.EXE" with arguments ""C:\Users\X\AppData\Local\Temp\X.doc" /q" with pid 3972
2018-08-02 08:50:00,890 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2018-08-02 08:50:00,937 [lib.api.process] ERROR: Unable to inject into 32-bit process with pid 3972, error: -12
2018-08-02 08:50:17,515 [lib.api.process] INFO: Successfully resumed process with pid 3972
```

it happens with pe and doc, not tested more formats, example of this one b573b6c322719046af76b16604d77576a741e2809f52bf78f855f1d1623a3f39, doc

any idea? i got newloader.exe and placed it instead of loader.exe(renamed obviosly)

**Comment by Spiralem** [comment]
I am curious if Windows 10 x64 is supported now?

**Comment by hackdefendr** [comment]
I found that the trick to getting Windows 10 x64 VM working under CAPE is to make sure UAC is fully disabled in the registry:

- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
- EnableLUA DWORD
- Set to 0 and reboot the VM.

Also it is good to disable Windows Defender and Real-time Protection from Group Policy.

Aside from this, I see no issues with using Windows 10 x64 as the guest.

**Comment by kevoreilly** [comment]
Check the process tree in the any run job. It spawns loads. In cape there is no spawned processes.

**Comment by hackdefendr** [comment]
Nope...I definitely see your point.  Any ideas of why that is?  64bit vs 32bit?

**Comment by kevoreilly** [comment]
Windows 10 largely works now - there will still be issues but they can be created individually when they arise.

**Comment by Spiralem** [comment]
> Windows 10 largely works now - there will still be issues but they can be created individually when they arise.

Is this with [https://github.com/ctxis/capemon](url) this monitor?

**Comment by doomedraven** [comment]
nop, https://github.com/kevoreilly/capemon check capev2 https://github.com/kevoreilly/CAPEv2
