### ISSUE TITLE
network activivty is off?

### ISSUE THREAD

**Issue by berloha** [ctxis/CAPE#78]
Hello?
On your site cape.contextis.com the network activity was no longer visible. No pcap in "Network Analysis" for all samples.

**Comment by kevoreilly** [comment]
Thanks for your message - I am working on getting this fixed (having some problems with the new rooter code).

**Comment by doomedraven** [comment]
ping me by email, i did port from v2 to cuckoo-mod so maybe i can help if you need ;)

**Comment by kevoreilly** [comment]
Thanks - I have emailed :-)

**Comment by kevoreilly** [comment]
Thanks - this will do for the public instance until we can resolve the problems with the new sniffer mods.

**Comment by kevoreilly** [comment]
Closing this as it pertains to the community instance which has been fixed temporarily pending a working sniffer.py with the recent rooter additions.

**Comment by doomedraven** [comment]
@kevoreilly did you fix rooter stuff? im about to look on it as i noted what there a lot of my original iptables missed and it do dns/udp leaks
