### ISSUE TITLE
VirusTotal downloads broken!

### ISSUE THREAD

**Issue by kevoreilly** [ctxis/CAPE#92]
The VirusTotal download function is broken due to some recent changes that I haven't yet had time to debug...

**Comment by doomedraven** [comment]
can you provide a bit more details? it could dig into it, working here

**Comment by doomedraven** [comment]
hm just checked and works on my case with changes to submission/views.py, so let me know if i can help you

**Comment by kevoreilly** [comment]
Sorry to be so vague - just wanted to note it before the weekend in case any one else has noted problems - will try and dig into it further next week!

**Comment by enzok** [comment]
i didn't commit your submission/views.py changes, and my VT download works fine.

**Comment by doomedraven** [comment]
hm interesting, i have the changes and it also works fine strange, maybe an log would be good

**Comment by kevoreilly** [comment]
It's probably me being a noob, let me double check on Sunday!

**Comment by kevoreilly** [comment]
Ok I found the problem - it was with whitelist-separated hashlists, I have fixed it by restoring some code I pushed a while back. Let me know if you see any problems, othewise I'll close this issue.

**Comment by doomedraven** [comment]
weird, how the hell it worked on my side %), sorry for that

**Comment by kevoreilly** [comment]
No worries :-)
